services:
  keycloak_db:
    image: postgres:15.3
    networks:  
      - nginx_network
    healthcheck:
      test: "exit 0"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak-data:/var/lib/postgresql/data
  keycloak_web:
    depends_on:
      keycloak_db:
        condition: service_healthy
    image: quay.io/keycloak/keycloak:22.0.1
    networks:  
      - nginx_network
    command: start --db postgres --db-url-host keycloak_db --db-username ${POSTGRES_USERNAME} --db-password ${POSTGRES_PASSWORD}
    expose: 
      - "8080"
    volumes:
      - './budgetsandboxtheme:/opt/keycloak/themes/budgetsandboxtheme'
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=login.budgetsandbox.com
      - KC_HOSTNAME_ADMIN=login.budgetsandbox.com
volumes:
  keycloak-data:
networks:
  nginx_network:
    external: true

  